# Generated by Django 3.0.4 on 2020-07-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('company', models.CharField(max_length=10)),
                ('mobile', models.BigIntegerField()),
                ('loc', models.CharField(max_length=10)),
            ],
        ),
    ]
